### ISSUE TITLE
Does not work with Raspberry Pi Camera Module 3

### ISSUE THREAD

**Issue by cHemingway** [roboportal/bot_box#15]
Hi,

I am trying to run this on Raspberry pi OS 64 bit (thanks for the update!) on a Pi4 with Camera Module 3, and a HDMI display.

On startup, it connects to the web portal, then immediately crashes with a GetUserMedia error. Here is the debug output:

```
2023/09/17 11:51:56 Arena: WS connected
2023/09/17 11:51:56 GetUserMedia error inappropriate ioctl for device
panic: inappropriate ioctl for device

goroutine 37 [running]:
github.com/roboportal/bot_box/pkg/arena.(*AnArena).Run(0x400011da00)
        /home/pi/bot_box/pkg/arena/arena.go:220 +0x1c10
created by main.main in goroutine 1
        /home/pi/bot_box/main.go:167 +0x8b4
```

With legacy camera support enabled instead, I get a similar error, though not exactly the same.
```
2023/09/17 11:58:45 GetUserMedia error Failed to start streaming: invalid argument
panic: Failed to start streaming: invalid argument

goroutine 23 [running]:
github.com/roboportal/bot_box/pkg/arena.(*AnArena).Run(0x40000ad860)
        /home/pi/bot_box/pkg/arena/arena.go:220 +0x1c10
created by main.main in goroutine 1
        /home/pi/bot_box/main.go:167 +0x8b4
```

**Comment by malykhin** [comment]
Hi @cHemingway,
Thank you for opening this issue.

As far as I can see, the error is coming from https://github.com/pion/mediadevices, specifically from its dependency: https://github.com/blackjack/webcam.

These packages only work with 'Legacy camera mode' on the new OS and do not support camera module v3.

We are working on an alternative camera driver for mediadevices based on libcamera. However, it will be a long process if successful.

**Comment by cHemingway** [comment]
Thanks for getting back to me. I am using the legacy camera mode as well as I suspected as such, but legacy camera mode still does not work, see my 2nd error message.

**Comment by malykhin** [comment]
Correct, it won’t work for both “non-legacy” mode and camera module v3

**Comment by cHemingway** [comment]
Ah sorry, didn't see that bit! Thanks for letting me know.
